const DESERT_ISLAND_ESCAPE=0;
const PUZZLE_LEAGUE=1;
const CAMPGROUND=2;
const RV=3;
const COOKIE=4;
const DLC_WA=5;
const DLC_JP_WA=6;
const WISP=7;
const HHD=8;
const WA=9;

const WELCOME_AMIIBO_FURNITURE=[ /* category, name_en, method */
	['name_es','24-hour-shop banner',RV],
	['name_es','24-hour-shop baskets',RV],
	['name_es','24-hour-shop clock',RV],
	['name_es','Accordion screen',RV],
	['name_es','Alto saxophone',RV],
	['name_es','Antique shelf',RV],
	['name_es','Balance beam',RV],
	['name_es','Bamboo bench',RV],
	['name_es','Banana flower basket',RV],
	['name_es','Barbecue spit',RV],
	['name_es','Barbell',RV],
	['name_es','Basic teacher\'s desk',RV],
	['name_es','Basket chair',RV],
	['name_es','Bath set',RV],
	['name_es','Beauty-salon cart',RV],
	['name_es','Big amp',RV],
	['name_es','Bistro table',RV],
	['name_es','Black phone',RV],
	['name_es','Blowfish sashimi',RV],
	['name_es','Blueprints',RV],
	['name_es','Board game',RV],
	['name_es','Bomb',RV],
	['name_es','Book stands',RV],
	['name_es','Boston bag',RV],
	['name_es','Bowl sink',RV],
	['name_es','Box with helmet',RV],
	['name_es','Bread basket',RV],
	['name_es','Bread-making set',RV],
	['name_es','Brown seat',RV],
	['name_es','Burger meal',RV],
	['name_es','Bus-stop stand',RV],
	['name_es','Busing station',RV],
	['name_es','Cafeteria table',RV],
	['name_es','Candelabra',RV],
	['name_es','Carpentry set',RV],
	['name_es','Cart return',RV],
	['name_es','Casablanca lilies',RV],
	['name_es','Cash tray',RV],
	['name_es','Chain divider',RV],
	['name_es','Changing room',RV],
	['name_es','Cheese',RV],
	['name_es','Cinnamoroll parasol',RV],
	['name_es','Cinnamoroll sign',RV],
	['name_es','Cinnamoroll sofa',RV],
	['name_es','Cinnamoroll stool',RV],
	['name_es','Cinnamoroll table',RV],
	['name_es','Cinnamoroll tray',RV],
	['name_es','Classic screen',RV],
	['name_es','Cloud-making machine',RV],
	['name_es','Coin locker',RV],
	['name_es','Compact car',RV],
	['name_es','Console table',RV],
	['name_es','Conveyor belt',RV],
	['name_es','Counter table',RV],
	['name_es','Crayons',RV],
	['name_es','Cucco ornament',RV],
	['name_es','Cup of tea',RV],
	['name_es','Cupcake',RV],
	['name_es','Curry plate',RV],
	['name_es','Cutting-board set',RV],
	['name_es','Daimyo\'s tray',RV],
	['name_es','Decorative plate',RV],
	['name_es','Desk bell',RV],
	['name_es','Desk mirror',RV],
	['name_es','Desktop TV',RV],
	['name_es','Dinnerware',RV],
	['name_es','Disk Writer',RV],
	['name_es','DJ K.K. booth',RV],
	['name_es','Doctor\'s desk',RV],
	['name_es','Document stack',RV],
	['name_es','Donburi',RV],
	['name_es','Donut box',RV],
	['name_es','Donut cushion',RV],
	['name_es','Drafting table',RV],
	['name_es','Drink machine',RV],
	['name_es','Durian flower basket',RV],
	['name_es','EKG machine',RV],
	['name_es','Electric bass',RV],
	['name_es','Elegant bench',RV],
	['name_es','Elegant chair',RV],
	['name_es','Espresso machine',RV],
	['name_es','Exam table',RV],
	['name_es','Fairy bottle',RV],
	['name_es','Fancy display case',RV],
	['name_es','Fancy tea set',RV],
	['name_es','Felyne Guardian',RV],
	['name_es','File cabinet (L)',RV],
	['name_es','File cabinet (M)',RV],
	['name_es','First-aid kit',RV],
	['name_es','Fish and chips',RV],
	['name_es','Floor light',RV],
	['name_es','Floor monitor',RV],
	['name_es','Floor seat',RV],
	['name_es','Forklift',RV],
	['name_es','Fruit drink',RV],
	['name_es','Fueki chair',RV],
	['name_es','Fueki drawers',RV],
	['name_es','Fueki pot',RV],
	['name_es','Fueki stereo',RV],
	['name_es','Fueki table',RV],
	['name_es','Futon mattress',RV],
	['name_es','Gadget shelf',RV],
	['name_es','GameCube drawer',RV],
	['name_es','Garden tools',RV],
	['name_es','Giant Game Boy',RV],
	['name_es','Gift pile',RV],
	['name_es','Glass partition',RV],
	['name_es','Glass screen',RV],
	['name_es','Glass teapot',RV],
	['name_es','Gossip Stone',RV],
	['name_es','Guitar case',RV],
	['name_es','Half-eaten pizza',RV],
	['name_es','Handbag',RV],
	['name_es','Hanger rack',RV],
	['name_es','Hanging chair',RV],
	['name_es','Hanging strap',RV],
	['name_es','Heart',RV],
	['name_es','Heart Container',RV],
	['name_es','Hearty breakfast',RV],
	['name_es','Heavy tome',RV],
	['name_es','Hello Kitty bed',RV],
	['name_es','Hello Kitty chair',RV],
	['name_es','Hello Kitty clock',RV],
	['name_es','Hello Kitty drawers',RV],
	['name_es','Hello Kitty planter',RV],
	['name_es','Hello Kitty table',RV],
	['name_es','Hero of Time scroll',RV],
	['name_es','Hot-snack case',RV],
	['name_es','Hunter',RV],
	['name_es','Hunter\'s cart',RV],
	['name_es','Hunter\'s hive',RV],
	['name_es','Hylian shield',RV],
	['name_es','Hyrulean treasure',RV],
	['name_es','Ice-cream display',RV],
	['name_es','Ikebana display',RV],
	['name_es','Imperial pot',RV],
	['name_es','Inkopolis chair',RV],
	['name_es','Inkopolis sign',RV],
	['name_es','Inkopolis table',RV],
	['name_es','Isabelle scooter',RV],
	['name_es','Item box',RV],
	['name_es','Ivy partition',RV],
	['name_es','Jail bars',RV],
	['name_es','Jewelry case',RV],
	['name_es','Kaiseki meal',RV],
	['name_es','Kerokerokeroppi cake',RV],
	['name_es','Kerokerokeroppi doll',RV],
	['name_es','Kerokerokeroppi tray',RV],
	['name_es','Kicks mat',RV],
	['name_es','Kiki and Lala bed',RV],
	['name_es','Kiki and Lala clock',RV],
	['name_es','Kiki and Lala sofa',RV],
	['name_es','Kiki and Lala table',RV],
	['name_es','Kitchen counter',RV],
	['name_es','Kitchen dishwasher',RV],
	['name_es','Kitchen refrigerator',RV],
	['name_es','Kitchen stove',RV],
	['name_es','Laboratory capsule',RV],
	['name_es','Lecture-hall bench',RV],
	['name_es','Lecture-hall desk',RV],
	['name_es','Left Splatfest sign',RV],
	['name_es','Light breakfast',RV],
	['name_es','Locker stack',RV],
	['name_es','Lon Lon milk',RV],
	['name_es','Lucky doll',RV],
	['name_es','Lunch box',RV],
	['name_es','Lunch pack',RV],
	['name_es','Massage recliner',RV],
	['name_es','Medicine cabinet',RV],
	['name_es','Meeting-room chair',RV],
	['name_es','Meeting-room table',RV],
	['name_es','Merchandise table',RV],
	['name_es','Metal box',RV],
	['name_es','Metal-rim table',RV],
	['name_es','Milk carton',RV],
	['name_es','Minifridge',RV],
	['name_es','Model bus',RV],
	['name_es','Model sailor',RV],
	['name_es','Modern cash register',RV],
	['name_es','Modern office chair',RV],
	['name_es','Modern wash station',RV],
	['name_es','Mug',RV],
	['name_es','Museum clock',RV],
	['name_es','Museum mat',RV],
	['name_es','My Melody bed',RV],
	['name_es','My Melody chair',RV],
	['name_es','My Melody clock',RV],
	['name_es','My Melody dresser',RV],
	['name_es','My Melody table',RV],
	['name_es','Nabiru ornament',RV],
	['name_es','Natural bench',RV],
	['name_es','Natural chair',RV],
	['name_es','Natural lamp',RV],
	['name_es','Natural low table',RV],
	['name_es','Natural table',RV],
	['name_es','NDS Lite bench',RV],
	['name_es','New 3DS - Isabelle',RV],
	['name_es','New 3DS - K.K.',RV],
	['name_es','New 3DS - Mabel',RV],
	['name_es','New 3DS - Sable',RV],
	['name_es','New 3DS - T&T',RV],
	['name_es','New 3DS XL - HHD',RV],
	['name_es','New Nintendo 3DS XL',RV],
	['name_es','Nintendo bench',RV],
	['name_es','Nintendo DSi bench',RV],
	['name_es','Nook\'s Homes car',RV],
	['name_es','Nook\'s Homes mat',RV],
	['name_es','Office cabinet',RV],
	['name_es','Office phone',RV],
	['name_es','Omelet',RV],
	['name_es','Operating-room cart',RV],
	['name_es','Organ',RV],
	['name_es','Otomon egg',RV],
	['name_es','Overflowing trash',RV],
	['name_es','PA system',RV],
	['name_es','Paella',RV],
	['name_es','Palico board',RV],
	['name_es','Pancakes',RV],
	['name_es','Pasta',RV],
	['name_es','Pastel low table',RV],
	['name_es','Perfume bottles',RV],
	['name_es','Piece of Heart',RV],
	['name_es','Pile of cash',RV],
	['name_es','Plant partition',RV],
	['name_es','Plastic canister',RV],
	['name_es','Plastic file box',RV],
	['name_es','Pompompurin bed',RV],
	['name_es','Pompompurin chair',RV],
	['name_es','Pompompurin pudding',RV],
	['name_es','Pompompurin rack',RV],
	['name_es','Pompompurin table',RV],
	['name_es','Pompompurin TV',RV],
	['name_es','Poogie',RV],
	['name_es','Popcorn',RV],
	['name_es','Potato gratin',RV],
	['name_es','Public telephone',RV],
	['name_es','Pylon set',RV],
	['name_es','Quilted tapestry',RV],
	['name_es','Ramen',RV],
	['name_es','Re-Tail clock',RV],
	['name_es','Re-Tail mat',RV],
	['name_es','Reception chair',RV],
	['name_es','Reception counter',RV],
	['name_es','Reception window',RV],
	['name_es','Record box',RV],
	['name_es','Red cash register',RV],
	['name_es','Red Wing',RV],
	['name_es','Retro screen',RV],
	['name_es','Retro sign',RV],
	['name_es','Right Splatfest sign',RV],
	['name_es','Ring',RV],
	['name_es','Rolling cart',RV],
	['name_es','Rolling closet',RV],
	['name_es','Rolling file cart',RV],
	['name_es','Round cushion',RV],
	['name_es','Round pillow',RV],
	['name_es','Round-cloth table',RV],
	['name_es','Rover suitcase',RV],
	['name_es','Rupee',RV],
	['name_es','Sacks of money',RV],
	['name_es','Sales graph',RV],
	['name_es','Salon chair',RV],
	['name_es','Salon mirror stand',RV],
	['name_es','Sample case',RV],
	['name_es','Sausage',RV],
	['name_es','Scattered papers',RV],
	['name_es','School locker',RV],
	['name_es','Scooter',RV],
	['name_es','Serving cart',RV],
	['name_es','Set lunch',RV],
	['name_es','Sewing kit',RV],
	['name_es','Shaved ice',RV],
	['name_es','Shoe boxes',RV],
	['name_es','Shoe-polishing set',RV],
	['name_es','Shoji bench',RV],
	['name_es','Shop coffee machine',RV],
	['name_es','Shop ice-cream case',RV],
	['name_es','Shop mat',RV],
	['name_es','Silver mic',RV],
	['name_es','Simple panel',RV],
	['name_es','Single rose',RV],
	['name_es','Skateboard rack',RV],
	['name_es','Slipper rack',RV],
	['name_es','Snack machine',RV],
	['name_es','Snare drum',RV],
	['name_es','Sound mixer',RV],
	['name_es','Speaker',RV],
	['name_es','Splatoon spawn point',RV],
	['name_es','Splatoon tower',RV],
	['name_es','Splattershot',RV],
	['name_es','Sports car',RV],
	['name_es','Square minitable',RV],
	['name_es','Squid bumper',RV],
	['name_es','Stack of books',RV],
	['name_es','Stack of clothes',RV],
	['name_es','Stacked magazines',RV],
	['name_es','Standing sink',RV],
	['name_es','Standing TV',RV],
	['name_es','Steamed lobster',RV],
	['name_es','Stone lantern',RV],
	['name_es','Strapped books',RV],
	['name_es','Stretcher',RV],
	['name_es','Super Sea Snail',RV],
	['name_es','Sushi bench',RV],
	['name_es','Sushi tray',RV],
	['name_es','Synthesizer',RV],
	['name_es','Table with cloth',RV],
	['name_es','Tacos',RV],
	['name_es','Tart',RV],
	['name_es','Termina\'s moon',RV],
	['name_es','Theater seat',RV],
	['name_es','Tile screen',RV],
	['name_es','Tong-and-tray stand',RV],
	['name_es','Tool cart',RV],
	['name_es','Tool shelf',RV],
	['name_es','Tool stand',RV],
	['name_es','Towel basket',RV],
	['name_es','Toy piano',RV],
	['name_es','Tractor',RV],
	['name_es','Train seat',RV],
	['name_es','Tranquil bridge',RV],
	['name_es','Trellis',RV],
	['name_es','Trumpet',RV],
	['name_es','Udon soup',RV],
	['name_es','Umbrella stand',RV],
	['name_es','Video camera',RV],
	['name_es','Villager statue',RV],
	['name_es','Waiting-room bench',RV],
	['name_es','Wall-mounted TV',RV],
	['name_es','Warming buffet',RV],
	['name_es','Wendell\'s painting',RV],
	['name_es','White office desk',RV],
	['name_es','Wii Remote cabinet',RV],
	['name_es','Wyvern eggs',RV],
	['name_es','Xylophone',RV],
	['name_es','Yarn basket',RV],
	['name_es','Zen backpack',RV],
	['name_es','Zen chair',RV],
	['name_es','Zen cupboard',RV],
	['name_es','Zen cushion',RV],
	['name_es','Zen desk',RV],
	['name_es','Zen low table',RV],
	['name_es','Zen phone stand',RV],
	['name_es','Zen screen',RV],
	['name_es','Zen tea set',RV]
];

const ARRAY1=[
	['piano de juguete','toy piano',WA],
	['camilla hospital','exam table',WA],
	['teléfono oficina','office phone',WA],
	['campanilla de hotel','desk bell',WA],
	['cubo de madera','wooden bucket',CAMPGROUND],
	['zumo de coco','coconut juice',CAMPGROUND],
	['sopa instantánea','ramen cup',CAMPGROUND],
	['pila de leña','firewood',CAMPGROUND],
	['menú hamburguesa','burger meal',WA],
	['candelabro de mesa','candelabra',WA],
	['cajón de reparto','metal box',WA],
	['lavabo tradicional','standing sink',WA],
	['anillo de compromiso','ring',WA],
	['aire acond. exterior','air purifier',CAMPGROUND],
	['biombo típico','classic screen',WA],
	['tabla de sushi','sushi tray',WA],
	['sintetizador','synthesizer',WA],
	['caja de herramientas','toolbox',CAMPGROUND],
	['cesta de toallas','towel basket',WA],
	['asidero de tren','hanging strap',WA],
	['cesta de ovillos','yarn basket',WA],
	['mesa de maestro','basic teacher\'s desk',WA],
	['asiento de tren','train seat',WA],
	['pizza a domicilio','whole pizza',CAMPGROUND],
	['macetero separador','plant partition',WA],
	['sopa de fideos','ramen',WA],
	['tarta','tart',WA],
	['juego de té pomposo','fancy tea set',WA],
	['juego lanzar aros','ringtoss',CAMPGROUND],
	['bola de musgo','moss ball',CAMPGROUND],
	['manguera de jardín','hose reel',CAMPGROUND],
	['mini-invernadero','greenhouse box',CAMPGROUND],
	['trattore','tractor',WA],
	['oso de madera','wooden bear',CAMPGROUND],
	['muñeco japonés','lucky doll',WA],
	['mesa de caligrafía','zen desk',WA],
	['centro de flores','ikebana display',WA],
	['carrito del correo','rolling cart',WA],
	['estantería antigua','antique shelf',WA],
	['cinta transportadora','conveyor belt',WA],
	['bomba de aire','air pump',CAMPGROUND],
	['pila de libros','stack of books',WA],
	['cesta de pan','bread basket',WA],
	['desayuno ligero','light breakfast',WA],
	['desayuno continental','hearty breakfast',WA],
	['torre de tortitas','pancakes',WA],
	['mostrador de helados','ice-cream display',WA],
	['regadera metálica','tin watering can',CAMPGROUND],
	['botiquín','first-aid kit',WA],
	['bidón de leche','milk canister',CAMPGROUND],
	['plato bolas arroz','rice balls',CAMPGROUND],
	['montón de billetes','pile of cash',WA],
	['jarra metálica','silver teapot',CAMPGROUND],
	['bandeja de sushi','sushi container',CAMPGROUND],
	['pila fardos arroz','rice bales',CAMPGROUND],
	['planta tropical','pitcher plant',CAMPGROUND],
	['futón','futon mattress',WA],
	['tentempié oriental','zen tea set',WA],
	['campanilla trepadora','trellis',WA],
	['bolsa de viaje','Boston bag',WA],
	['patinete','kick scooter',CAMPGROUND],
	['fiambrera con mantel','lunch box',WA],
	['cartón abrefácil','milk carton',WA],
	['mesa de terraza','bistro table',WA],
	['bidón de gasolina','plastic canister',WA],
	['carretilla elevadora','forklift',WA],
	['valla de conos','pylon set',WA],
	['barra de pesas','barbell',WA],
	['cápsula experimental','laboratory capsule',WA],
	['archivador grande','file cabinet (L)',WA],
	['archivador mediano','file cabinet (M)',WA],
	['carrito archivador','rolling file cart',WA],
	['mampara acordeón','accordion screen',WA],
	['silla de aluminio','metal-and-wood chair',CAMPGROUND],
	['reja de prisión','jail bars',WA],
	['registradora gris','modern cash register',WA],
	['probador','changing room',WA],
	['muslo de dinosaurio','roasted dino meat',CAMPGROUND],
	['estatua de aldeano','villager statue',WA],
	['tarima tablillas','wooden duckboards',CAMPGROUND],
	['nido de golondrina','sparrow\'s nest',CAMPGROUND],
	['balancín de jardín','swinging bench',CAMPGROUND],
	['monitor de ordenador','desktop TV',WA],
	['tarima pequeña','platform',CAMPGROUND],
	['barra de gimnasia','balance beam',WA],
	['pelota de ejercicios','exercise ball',CAMPGROUND],
	['mesa con mantel','table with cloth',WA],
	['vajilla','dinnerware',WA],
	['mesa de delineante','drafting table',WA],
	['perchero de barra','hanger rack',WA],
	['mesita color pastel','pastel low table',WA],
	['tabla cortar pescado','fish on a board',CAMPGROUND],
	['pizarra con menú','menu chalkboard',CAMPGROUND],
	['mostrador de madera','wooden counter',CAMPGROUND],
	['monociclo','unicycle',CAMPGROUND],
	['toallero plegable','towel rack',CAMPGROUND],
	['mesa de aluminio','metal-and-wood table',CAMPGROUND],
	['armario con ruedas','rolling closet',WA],
	['asta de bandera','metal flagpole',CAMPGROUND],
	['maizal','cornstalks',CAMPGROUND],
	['lavabo tipo bol','bowl sink',WA],
	['balón','ball',CAMPGROUND],
	['mampara de cristal','glass partition',WA],
	['ciprés','cypress plant',CAMPGROUND],
	['vitrina floristería','flower display case',CAMPGROUND],
	['puesto autoservicio','tong-and-tray stand',WA],
	['gratinado de patatas','potato gratin',WA],
	['paragüero','umbrella stand',WA],
	['lata metálica','metal can',CAMPGROUND],
	['tocador de madera','salon mirror stand',WA],
	['silla de plástico','garden chair',CAMPGROUND],
	['bolsa de la compra','shopping bag',CAMPGROUND],
	['mesita con tapete','zen phone stand',WA],
	['parterre','flower bed',CAMPGROUND],
	['caja de arena','sandbox',DLC_WA],
	['mesa de plástico','garden table',CAMPGROUND],
	['señal de tráfico','do-not-enter sign',CAMPGROUND],
	['pilón','handwashing area',CAMPGROUND],
	['sujetalibros','book stands',WA],
	['equipo quirúrgico','operating-room cart',WA],
	['cama de hospital','modern hospital bed',CAMPGROUND],
	['sillón oficina','modern office chair',WA],
	['basura','trash bags',CAMPGROUND],
	['silla doble de aula','lecture-hall bench',WA],
	['pupitre','lecture-hall desk',WA],
	['mesa de reunión','meeting-room table',WA],
	['taburete de trabajo','box-shaped seat',CAMPGROUND],
	['mesa de trabajo','worktable',CAMPGROUND],
	['nevera pequeña','minifridge',WA],
	['camilla ambulancia','stretcher',WA],
	['cajonera oficina','office cabinet',WA],
	['caja de ceras','crayons',WA],
	['teléfono baquelita','black phone',WA],
	['bobina de cable','cable spool',CAMPGROUND],
	['set de béisbol','baseball set',CAMPGROUND],
	['reloj oficina','office clock',CAMPGROUND],
	['adorno floral','flower wreath',CAMPGROUND],
	['aloe pequeño','succulent plant',CAMPGROUND],
	['silla de reunión','meeting-room chair',WA],
	['teléfono público','public telephone',WA],
	['equipo de peluquería','beauty-salon cart',WA],
	['caja de caudales','money box',CAMPGROUND],
	['mesita de té','zen low table',WA],
	['mesa de operaciones','operating table',CAMPGROUND],
	['mesa de mercancías','merchandise table',WA],
	['escritorio médico','doctor\'s desk',WA],
	['raqueta de tenis','tennis racket',CAMPGROUND],
	['bandeja con cambio','cash tray',WA],
	['micrófono de mesa','desktop mic',CAMPGROUND],
	['pila de neumáticos','tire stack',CAMPGROUND],
	['taquilla de escuela','school locker',WA],
	['taquilla de monedas','coin locker',WA],
	['atril de conferencia','lectern with mic',CAMPGROUND],
	['montón de regalos','gift pile',WA],
	['mochila escolar','zen backpack',WA],
	['vitrina antigüedades','fancy display case',WA],
	['cubo de palomitas','popcorn',WA],
	['silla de bar moderna','counter seat',CAMPGROUND],
	['silla de bar añeja','zen chair',WA],
	['mampara restaurante','glass screen',WA],
	['puesto bandejas','busing station',WA],
	['mesa camilla','round-cloth table',WA],
	['banco sala de espera','waiting-room bench',WA],
	['mesa restaurante','square minitable',WA],
	['mesa terraza metal','metal-rim table',WA],
	['reja verde','green net',CAMPGROUND],
	['mesa tronco','wood-plank table',CAMPGROUND],
	['archivador plástico','plastic file box',WA],
	['silla de forja','iron garden chair',CAMPGROUND],
	['mesa de forja','iron garden table',CAMPGROUND],
	['menú infantil','kiddie meal',CAMPGROUND],
	['tele plana de pared','wall-mounted TV',WA],
	['tablón de avisos','billboard',CAMPGROUND],
	['jarra termo','water pot',CAMPGROUND],
	['ropa planchada','stack of clothes',WA],
	['máquina expendedora','snack machine',WA],
	['saxofón','alto saxophone',WA],
	['lavabo rural','retro sink',CAMPGROUND],
	['set de perfumes','perfume bottles',WA],
	['lote de conservas','cans',CAMPGROUND],
	['gas propano','propane tanks',CAMPGROUND],
	['mampara oriental','zen screen',WA],
	['mampara de bambú','bamboo fence',CAMPGROUND],
	['butaca de masaje','massage recliner',WA],
	['barril japonés','zen barrel',CAMPGROUND],
	['silla de recepción','reception chair',WA],
	['máquina de refrescos','drink machine',WA],
	['tambor redoblante','snare drum',WA],
	['consola Wii U (blanca)','Wii U console (white)',COOKIE],
	['consola Wii U (negra)','Wii U console (black)',COOKIE],
	['pila de documentos','document stack',WA],
	['silla imperial','imperial chair',CAMPGROUND],
	['bebida refrescante','fruit drink',WA],
	['granizado','shaved ice',WA],
	['butaca cine','theater seat',WA],
	['contenedor de basura','garbage bin',CAMPGROUND],
	['guardapantuflas','slipper rack',WA],
	['plancha de cocina','teppanyaki grill',CAMPGROUND],
	['registradora pequeña','red cash register',WA],
	['horno de piedra','brick oven',CAMPGROUND],
	['bolso chic','handbag',WA],
	['micrófono vocal','silver mic',WA],
	['órgano eléctrico','organ',WA],
	['xilófono','xylophone',WA],
	['trompeta','trumpet',WA],
	['mesa de sonido','sound mixer',WA],
	['encimera de cocina','kitchen counter',WA],
	['nevera industrial','kitchen refrigerator',WA],
	['menú de pared','sushi menu',CAMPGROUND],
	['bajo eléctrico','electric bass',WA],
	['mesa de bar','cafeteria table',WA],
	['carrito de servicio','serving cart',WA],
	['mostrador recepción','reception counter',WA],
	['rótulo de pie','outdoor sign',CAMPGROUND],
	['montón de revistas','stacked magazines',WA],
	['reloj tijera','narrow clock',DLC_WA],
	['silla estuche','pen-case chair',DLC_WA],
	['expositor de madera','wood display stand',CAMPGROUND],
	['expositor informal','casual display stand',CAMPGROUND],
	['expositor ostentoso','fancy display stand',CAMPGROUND],
	['expositor sencillo','basic display stand',CAMPGROUND],
	['estante alimentación','store shelf',CAMPGROUND],
	['punto de luz suelo','floor light',WA],
	['asiento fofo doble','brown seat',WA],
	['fiambrera','lunch pack',WA],
	['menú japonés','set lunch',WA],
	['expositor patinetes','skateboard rack',WA],
	['escritorio oficina','white office desk',WA],
	['papelera práctica','basic trash can',CAMPGROUND],
	['sillón de peluquería','salon chair',WA],
	['bandeja japonesa','daimyo\'s tray',WA],
	['jarrón con rosa','single rose',WA],
	['taza grande','mug',WA],
	['caja de vinilos','record box',WA],
	['bicicleta de paseo','cruiser bike',CAMPGROUND],
	['amplificador grande','big amp',WA],
	['cámara de vídeo','video camera',WA],
	['altavoz','speaker',WA],
	['lavavajillas exprés','kitchen dishwasher',WA],
	['estante botica','medicine cabinet',WA],
	['plato de salchichas','sausage',WA],
	['cadena de separación','chain divider',WA],
	['equipo de jardinería','garden tools',WA],
	['carro herramientas','tool cart',WA],
	['portería','soccer goal',DLC_WA],
	['rótulo colgante','electric sign',CAMPGROUND],
	['rótulo de pared','round electric sign',CAMPGROUND],
	['espejo de tocador','desk mirror',WA],
	['taquilla seguridad','locker stack',WA],
	['grifo de jardín','garden faucet',CAMPGROUND],
	['macetero barril','barrel planter',CAMPGROUND],
	['roca gruesa','garden rock',CAMPGROUND],
	['roca alta','tall garden rock',CAMPGROUND],
	['banco funcional','natural bench',WA],
	['sillón funcional','natural chair',WA],
	['mesa funcional','natural table',WA],
	['mesita funcional','natural low table',WA],
	['lámpara funcional','natural lamp',WA],
	['silla elegante','elegant chair',WA],
	['banco elegante','elegant bench',WA],
	['coche compacto','compact car',WA],
	['coche deportivo','sports car',WA],
	['piatto di fritti','fish and chips',WA],
	['plato de pasta','pasta',WA],
	['tabla de quesos','cheese',WA],
	['plato de tacos','tacos',WA],
	['cena japonesa','kaiseki meal',WA],
	['biombo enredadera','ivy partition',WA],
	['taza de té','cup of tea',WA],
	['bol de arroz japonés','donburi',WA],
	['mampara simple','simple panel',WA],
	['tabla de cortar','cutting-board set',WA],
	['equipo de panadería','bread-making set',WA],
	['cocina industrial','kitchen stove',WA],
	['vitrina con ruedas','sample case',WA],
	['barra mostrador','counter table',WA],
	['vitrina joyería','jewelry case',WA],
	['señuelo para patos','decoy duck',CAMPGROUND],
	['plato de curry indio','curry plate',WA],
	['ducha de pared','modern wash station',WA],
	['set de autógrafos','autograph cards',CAMPGROUND],
	['plato decorativo','decorative plate',WA],
	['mampara azulejos','tile screen',WA],
	['monitor de escenario','floor monitor',WA],
	['correa portalibros','strapped books',WA],
	['juego de tablero','board game',WA],
	['estantería metálica','tool shelf',WA],
	['set de aseo japonés','bath set',WA],
	['electrocardiógrafo','EKG machine',WA],
	['banco TV','zen cupboard',WA],
	['jarrón de azucenas','Casablanca lilies',WA],
	['bol de udon','udon soup',WA],
	['caja de dónuts','donut box',WA],
	['carpaccio de pescado','blowfish sashimi',WA],
	['sandía','watermelon',CAMPGROUND],
	['langosta cocida','steamed lobster',WA],
	['tortilla francesa','omelet',WA],
	['paella','paella',WA],
	['mampara añeja','retro screen',WA],
	['banco de bambú','bamboo bench',WA],
	['parada de bus','bus-stop stand',WA],
	['taquilla de zapatos','shoe locker',CAMPGROUND],
	['ventanilla recepción','reception window',WA],
	['bandeja de bufé','warming buffet',WA],
	['cupcake','cupcake',WA],
	['tetera de cristal','glass teapot',WA],
	['cafetera exprés','espresso machine',WA],
	['silla sin patas','floor seat',WA],
	['wok','imperial pot',WA],
	['consola de madera','console table',WA],
	['asiento de mimbre','round pillow',WA],
	['silla suspendida','hanging chair',WA],
	['farol de jardín','garden lantern',CAMPGROUND],
	['estantería de baño','bathroom shelf',CAMPGROUND],
	['scooter','scooter',WA],
	['cojín redondo','round cushion',WA],
	['silla redonda ratán','basket chair',WA],
	['cojín con borlas','zen cushion',WA],
	['montón de papeles','scattered papers',WA],
	['mesa de té redonda','large tea table',CAMPGROUND],
	['New Nintendo 3DS','New Nintendo 3DS',COOKIE],
	['New Nintendo 3DS XL','New Nintendo 3DS XL',WA],
	['Wii U Station','Wii U Station',DESERT_ISLAND_ESCAPE],
	['Nintendo 3DS Station','Nintendo 3DS Station',PUZZLE_LEAGUE],
	['estante juegos Wii U','Wii U game shelf',DESERT_ISLAND_ESCAPE],
	['estante juegos 3DS','Nintendo 3DS shelf',PUZZLE_LEAGUE],
	['estante amiibo','amiibo shelf',DESERT_ISLAND_ESCAPE],
	['Disk Writer','Disk Writer',WA],
	['tele Game Boy','giant Game Boy',WA],
	['asador barbacoa','barbecue spit',WA],
	['nido de wyvern','Wyvern eggs',WA],
	['cazador','hunter',WA],
	['espada Ala roja','Red Wing',WA],
	['estatua Felyne','Felyne Guardian',WA],
	['carreta de caza','hunter\'s cart',WA],
	['tablón Felyne','Palico board',WA],
	['caja de objetos','item box',WA],
	['Poogie','Poogie',WA],
	['panal de caza','hunter\'s hive',WA],
	['banco rollo sushi','sushi bench',WA],
	['frigo de helados','shop ice-cream case',WA],
	['portacestas súper','24-hour-shop baskets',WA],
	['banderola súper','24-hour-shop banner',WA],
	['nevera precocinados','hot-snack case',WA],
	['cafetera súper','shop coffee machine',WA],
	['pastel gigante','massive cake',HHD,1],
	['casita de chuches','candy house',HHD,1],
	['ovni','UFO',HHD,1],
	['hormiga gigante','giant ant',HHD,1],
	['montaña','mountain',HHD,1],
	['iceberg','iceberg',HHD,1],
	['Sol','sun',HHD,1],
	['montaña de billetes','mountain of money',HHD,1],
	['olla gigante','giant stew pot',HHD,1],
	['carruaje','carriage',HHD,1],
	['taza de café gigante','teacup ride',HHD,1],
	['papá oso gigante','giant teddy bear',HHD,1],
	['robot gigante','robot hero',HHD,1],
	['torre de monitores','monitor tower',HHD,1],
	['tienda','tent',HHD,1],
	['avión de hélice','propeller plane',HHD,1],
	['submarino','submarine',HHD,1],
	['coche de lujo','luxury car',HHD,1],
	['huevo gigante','large egg',HHD,1],
	['objeto hinchable','inflatable Resetti',HHD,1],
	['reloj árbol plaza','sapling clock',DESERT_ISLAND_ESCAPE],
	['supermolusco','Super Sea Snail',WA],
	['cartel Cromópolis','Inkopolis sign',WA],
	['mesa Cromópolis','Inkopolis table',WA],
	['torreta Cromópolis','Splatoon tower',WA],
	['calamar hinchable','squid bumper',WA],
	['silla Cromópolis','Inkopolis chair',WA],
	['Lanzatintas B','Splattershot',WA],
	['panel izq. Splatoon','left Splatfest sign',WA],
	['panel der. Splatoon','right Splatfest sign',WA],
	['punto base Splatoon','Splatoon spawn point',WA],
	['tele con mueble','standing TV',WA],
	['mapa isla desierta','Desert Island map',DESERT_ISLAND_ESCAPE],
	['sartén','frying pan',DESERT_ISLAND_ESCAPE],
	['mesa isla desierta','Desert Island table',DESERT_ISLAND_ESCAPE],
	['silla isla desierta','Desert Island stool',DESERT_ISLAND_ESCAPE],
	['cómoda Hello Kitty','Hello Kitty drawers',WA],
	['maceta Hello Kitty','Hello Kitty planter',WA],
	['cama Hello Kitty','Hello Kitty bed',WA],
	['mesa Hello Kitty','Hello Kitty table',WA],
	['silla Hello Kitty','Hello Kitty chair',WA],
	['reloj Hello Kitty','Hello Kitty clock',WA],
	['reloj Hello Kitty','Hello Kitty clock',WA],
	['cama My Melody','My Melody bed',WA],
	['reloj My Melody','My Melody clock',WA],
	['reloj My Melody','My Melody clock',WA],
	['mecedora My Melody','My Melody chair',WA],
	['tocador My Melody','My Melody dresser',WA],
	['mesita My Melody','My Melody table',WA],
	['cama Pompompurin','Pompompurin bed',WA],
	['silla Pompompurin','Pompompurin chair',WA],
	['estante Pompompurin','Pompompurin rack',WA],
	['mesita Pompompurin','Pompompurin table',WA],
	['flan Pompompurin','Pompompurin pudding',WA],
	['tele Pompompurin','Pompompurin TV',WA],
	['tele Pompompurin','Pompompurin TV',WA],
	['cama Kiki & Lala','Kiki and Lala bed',WA],
	['reloj Kiki & Lala','Kiki and Lala clock',WA],
	['reloj Kiki & Lala','Kiki and Lala clock',WA],
	['mesa Kiki & Lala','Kiki and Lala table',WA],
	['sofá Kiki & Lala','Kiki and Lala sofa',WA],
	['máquina de nubes','cloud-making machine',WA],
	['mesita Cinnamoroll','Cinnamoroll table',WA],
	['parasol Cinnamoroll','Cinnamoroll parasol',WA],
	['sofá Cinnamoroll','Cinnamoroll sofa',WA],
	['cartel Cinnamoroll','Cinnamoroll sign',WA],
	['taburete Cinnamoroll','Cinnamoroll stool',WA],
	['bandeja Cinnamoroll','Cinnamoroll tray',WA],
	['bandeja jardín zen','Kerokerokeroppi tray',WA],
	['pastelito jardín zen','Kerokerokeroppi cake',WA],
	['farol jardín zen','stone lantern',WA],
	['puente jardín zen','tranquil bridge',WA],
	['tarima jardín zen','shoji bench',WA],
	['muñeca de papel','Kerokerokeroppi doll',WA],
	['New 3DS XL HHD','New 3DS XL - HHD',WA],
	['New 3DS Canela','New 3DS - Isabelle',WA],
	['New 3DS Pili','New 3DS - Mabel',WA],
	['New 3DS Mili','New 3DS - Sable',WA],
	['New 3DS Totakeke','New 3DS - K.K.',WA],
	['New 3DS T&N','New 3DS - T&T',WA],
	['coche inmobiliaria','Nook\'s Homes car',WA],
	['moto de Canela','Isabelle scooter',WA],
	['bomba','bomb',WA],
	['hada en una botella','fairy bottle',WA],
	['cofre tesoro hyliano','Hyrulean treasure',WA],
	['cuco','Cucco ornament',WA],
	['piedra chismosa','Gossip Stone',WA],
	['corazón','Heart',WA],
	['contenedor corazón','Heart Container',WA],
	['pieza de corazón','Piece of Heart',WA],
	['leche Lon Lon','Lon Lon milk',WA],
	['luna de Términa','Termina\'s moon',WA],
	['escudo hyliano','Hylian shield',WA],
	['leyenda del héroe','Hero of Time scroll',WA],
	['rupia','Rupee',WA],
	['miniautobús','model bus',WA],
	['minibarca','model sailor',WA],
	['banco Nintendo','Nintendo bench',WA],
	['figura chihuahua','Chihuahua ornament',COOKIE],
	['figura dálmata','Dalmatian ornament',COOKIE],
	['estatua teckel','Dachshund ornament',COOKIE],
	['figura labrador','Labrador ornament',COOKIE],
	['cómoda GameCube','GameCube drawer',WA],
	['armario mando de Wii','Wii Remote cabinet',WA],
	['sofá DS Lite','NDS Lite bench',WA],
	['sofá Nintendo DSi','Nintendo DSi bench',WA],
	['estanque japonés','lotus pond',DLC_WA],
	['reloj súper','24-hour-shop clock',WA],
	['cojín rosquilla','donut cushion',WA],
	['huevo de Otomon','Otomon egg',WA],
	['adorno de Navirou','Nabiru ornament',WA],
	['cazuela Fueki','Fueki pot',WA],
	['silla Fueki','Fueki chair',WA],
	['cajonera Fueki','Fueki drawers',WA],
	['cadena Fueki','Fueki stereo',WA],
	['mesa Fueki','Fueki table',WA],
	['cojín Puzzle League','fruit-panel cushion',PUZZLE_LEAGUE],
	['kit de costura','sewing kit',WA],
	['colcha decorativa','quilted tapestry',WA],
	['cesta con durián','durian flower basket',WA],
	['cesta con plátano','banana flower basket',WA],
	['cartel antiguo','retro sign',WA],
	['fila de carritos','cart return',WA],
	['caja con cascos','box with helmet',WA],
	['caja de pizza','half-eaten pizza',WA],
	['papelera rebosante','overflowing trash',WA],
	['maleta de Fran','Rover suitcase',WA],
	['tarta 2017','2017 cake',DLC_JP_WA],
	['árbol festivo nevado','white festive tree',DLC_WA],
	['tocho','heavy tome',WA],
	['reloj museo','museum clock',WA],
	['equipo electrónica','gadget shelf',WA],
	['pila bolsas de bayas','sacks of money',WA],
	['gráfico de ventas','sales graph',WA],
	['alfomb. inmobiliaria','Nook\'s Homes mat',WA],
	['reloj reciclaje','Re-Tail clock',WA],
	['alfombra reciclaje','Re-Tail mat',WA],
	['plano restauración','carpentry set',WA],
	['equipo de carpintero','tool stand',WA],
	['alfombra zapatería','Kicks mat',WA],
	['pila cajas zapatos','shoe boxes',WA],
	['kit limpieza calzado','shoe-polishing set',WA],
	['micrófono megafonía','PA system',WA],
	['tablón planos','blueprints',WA],
	['mesa DJ KeKe','DJ K.K. booth',WA],
	['estuche de guitarra','guitar case',WA],
	['alfombra tienda','shop mat',WA],
	['alfombra museo','museum mat',WA],
	['maqueta inmobiliaria','Nook\'s Homes model',HHD],
	['cuadro de Da Morsi','Wendell\'s painting',WA],
	['lámpara mágica','magic lamp',WISP],
	['amuleto','good-luck charm',DESERT_ISLAND_ESCAPE],
	['trofeo Ikada','Ikada trophy',DESERT_ISLAND_ESCAPE],
]/*.filter((itemInfo) => itemInfo[2] === WA)*/.reduce((acc, itemInfo) => {
	/* return only the ones that are in WELCOME_AMIIBO_FURNITURE */
	const found = WELCOME_AMIIBO_FURNITURE.find((waInfo) => waInfo[1].toLocaleLowerCase().localeCompare(itemInfo[1].toLocaleLowerCase()));
	if (!found) {
		acc.push(itemInfo);
	}
	return acc;
}, []);